/*global define*/
define({
    LOADING_UPDATE : 'Loading update info...',
    LATEST_LABEL : 'Latest:',
    DISLIKE : 'Wrong guess',
    UPDATE_ALL : 'One-click update',
    UPDATE_RECOMMENDED : 'Update all',
    UPDATE : 'Update',
    UPDATING : 'Update',
    COULD_UPDATE_TO : 'Update available',
    COULD_UPDATE : 'Update available',
    MANAGE_MY_APPS : 'Manage my apps',
    CONFIG : 'Settings',
    UPDATE_NOTIFI_FREQUENCE_WEEKLY : 'Weekly reminder',
    UPDATE_NOTIFI_FREQUENCE_DAYLY : 'Daily reminder',
    UPDATE_NOTIFI_FREQUENCE_NEVER : 'Don\'t ask again',
    CONFIRM_UNINSTALL_ON_DEVICE : 'Confirm uninstall on your device',
    MOVE : 'Move',
    CATEGORY : 'Category: ',
    VERSION_HISTORY : 'Version history',
    IGNORED_APPS : '{1} app update ignored',
    IGNORED_TITLE : 'Ignore update',
    ENABLE_APP_UPGRADE_TIP : 'You\'ve turned off the "Automatic Updates" feature, <span class="link button-open-update">Turn it on</span>',
    CHANGE_LOG_EMPRY : 'No update information',
    SUGGESTION_REF : 'Recommendation based on <span class="button-navigate-to-ref-page">{1}</span>',

    // START_SCAN : '开洗',
    // SCAN_TIP1 : '山寨应用有风险，广告应用很烦人！',
    // SCAN_TIP2 : '豌豆洗白白会帮您找出这些应用，并协助您把它们更换成官方版或没有广告的版本。',
    // SCAN_TIP3 : '尽情享受放心应用的乐趣吧！',
    // SCANNING : '正在准备洗澡水...',
    // SCANNING_TIP : '分析已安装应用',
    // QUERYING : '正在准备沐浴液...',
    // QUERYING_TIP : '查找可替换应用',
    // PIRATE_TIP : '山寨应用可替换为官方版',
    //ADS_NO_SOLUTION_TIP : '广告应用暂无替换方案',
    // ADS_TIP : '广告应用可替换为无广告版',
    // PIRATE : '山寨',
    // ADS : '广告',
    // REPLACE : '替换为正版',
    // RESULT_EMPTY : '本来就好白！',
    // RESULT_EMPTY_TIP : '太棒了！没有发现山寨应用和广告应用！',
    // RESULT_FINISH : '洗后变好白',
    // RESULT_FINISH_TIP : '没有山寨和广告应用的困扰，世界清静多了。',
    // RESULT_SUMMARY_POP_ADS : '洗好了！',
    // RESULT_SUMMARY_POP_ADS_TIP : '还有 {1} 个有通知栏广告的应用暂时没有替换方案，您可以看看是否需要卸载。',
    // UNINSTALL_ALL : '全部卸载',
    // DIRECT_ADS_TITLE : '本来就挺白！',
    // DIRECT_ADS_DESC : '没有发现山寨应用！</br>有 {1} 个有通知栏广告的应用暂时没有替换方案，您可以看看是否需要卸载。',
    // WASH_CONNECT_TIP : '需要 USB 连接模式才可以洗白白哦！',
    // WASH_SHARE : '去臭美一下',
    // APP_WASH_ERROR : '糟糕！停水了！',
    // WASH_ERROR_TIP : '洗白白的时候停水了，请检查您的网络连接后重试一下。',
    // WASH_RETRY : '再放一缸水',
    // WASH_SURVEY : '有豌豆没发现的脏应用？',
    // TELL_US : '告诉豌豆们吧！',

    EMPTY_TIP_WEB_APP_NOT_LOGIN : 'Do you want to view previously installed apps? Go <span class="button-login link">login to SnapPea</span> and you can get back your apps!',

    ALERT_TIP_CRITICAL_APP : '"{1}" can\'t be deleted. Deleting Android system apps can damage or "brick" your device.',
    ALERT_TIP_UNINSTALL_WIFI_CONFIRM : 'You\'re connected via Wi-Fi, please complete the install on your device.',
    ALERT_TIP_DEL_SYS_APP_CONFIRM : '<p>Uninstall the selected {1} system app? </p><p>Deleting Android system apps can damage or "brick" your device.</p>',
    ALERT_TIP_IGNORED_UPDATE_CONFIRM : 'Ignore this app update? After ignoring, you can still change your update settings later.',
    ALERT_TIP_MOVE_NEED_CONFIRM : 'Please confirm the app on your device',
    // ALERT_TIP_UPDATE_ILLEGAL : '<p>检测到「{1}」新版本和已安装版本签名不一致。</p><p>如果您选择继续升级，豌豆荚会帮您先删除旧版本再安装，这样原来的应用数据和游戏存档将会丢失。</p><p>是否继续？</p>',
    // ALERT_TIP_UPDATE_NOT_RECOMMENDED : '<p>{1}</p><p>是否继续？</p>',
    // ALERT_TIP_UPDATE_ILLEGAL_SYSTEM_UNROOT : '<p>检测到「{1}」新版本和已安装版本签名不一致。</p><p>由于此应用是一个系统应用，豌豆荚需要 root 权限才能为您升级此应用。</p><p>是否继续？</p>',
    SD_MOUNT_TIP : 'Because your device is connected as a USB storage device, SnapPea cannot display the apps installed on your device. Please change your settings and try again.',
    SD_MOUNT_TIP2 : 'Because your device is connected as a USB storage device, SnapPea cannot read the apps stored on your SD card.',
    FLASH_TIP_TIP : 'Did you flash your device? SnapPea can help you restore your data in no time. <span class="button-flash link">Try it now!</span>',

    ONE_KEY_UPDATE : 'One-click update ({1})',
    ONE_KEY_UPDATE_DES : 'Found {1} app(s) to update',
    UPDATE_DES : '{1} app(s) to update',
    ONE_KEY_TRANSFER : 'One-click move ({1})',
    ONE_KEY_TRANSFER_DES : 'Move files to your SD card to make space on your device\'s internal storage',

    WEB_APPS : 'Downloaded apps ({1})',
    WEB_APPS_EMPTY : 'Downloaded apps',
    WEB_APPS_EMPTY_TIP_PRE : 'You haven\'t downloaded any apps yet',
    WEB_APPS_EMPTY_TIP_LINK : 'Find great apps',
    WEB_APPS_EMPTY_TIP_POST : 'Go download',
    APP_SEARCH : 'App search',
    UNINSTALL_AFTER_HIDE : '"{1}" was deleted from your download history. Delete this app on your phone?',
    WEB_APPS_HIDE_TEXT : 'Hide',
    WEB_APPS_HIDE_FAILED_TEXT : 'Failed to hide',

    APP_WASH : 'App scan',
    APP_WASH_DES : 'Scan your apps and remove any fakes or apps with ads!',

    LIKE : 'Like',
    UNLIKE : 'Dislike',
    COMMENTARY_PLACEHOLDER : 'My review...',
    COMMENTARY : 'Comment',
    MODIFY : 'Change',
    SEND_SUCCESS : 'Comment added',
    SEND_FAILED : 'Comment failed',
    DOWNLOAD_COUNT : 'Download count',
    DOWNLOAD_COUNT_TIP : '{1} times',
    NO_SPECIAL_PERMISSION : 'No special permissions',
    BATCH_APP_TITLE : '{1} apps selected',

    ADDING_LOCAL_APK : 'Importing app(s), please wait...',
    UPDATEING_ALL : 'Updating...',
    APP_NOT_INDEXED : 'Sorry, SnapPea hasn\'t indexed that app yet',
    LOOK_FOR_DETAIL : 'Check app details',

    COL_NAME_LABEL : 'Name',
    COL_RATE_LABEL : 'Feedback rate',
    COL_VERSION_LABEL : 'Version',
    COL_INSTALL_TIME : 'Install date',
    COL_INSTALL_POSITION : 'Location',
    INSTALL_POSITION_LABEL : 'Location: ',

    BUTTON_ADD_APP_LABEL : 'Install apps',


    BUTTON_MOVE_TO_DEVICE_LABEL : 'Move to internal storage',

    APK_SELECTOR_DISCRIPTION_TEXT : 'Select an APK file or folder',

    UNINSTALL_TIP : 'Uninstall the {1} selected apps?',
    MOVE_TO_SD_CARD : 'Move {1} app(s) to SD card?',
    MOVE_TO_DEVICE : 'Move {1} apps to internal storage?',
    UPGRADE_TIP_TEXT : 'Update {1} app(s)?',

    NON_USER_APPS_TEXT : '<div>Oh? You haven\'t installed any apps on your phone yet.</div>',
    NON_SYSTEM_APPS_TEXT : 'Your device doesn\'t have any system apps installed',
    NON_UPGRADE_APPS_TEXT : 'All your apps are up-to-date. Yay! ',
    UPGRADE_TIP : 'We currently can\'t update apps for your device, but we\'re working on it...',

    IGNORED : 'Ignored',

    DELETE_APK_WHEN_FINISH : 'Delete local APK files after installing',

    ONE_KEY_TRANSFER_TITLE : 'One-click move',
    INSTALL : 'Install',
    INSTALLING : 'Installing',
    UNINSTALL : 'Uninstall',
    VERSION : 'Version: ',
    LATEST_VERSION : 'Latest version: ',
    LATEST_VERSION_SIZE : 'Version size: ',
    SIZE : 'Size: ',
    PERMISSON : 'Permissions: ',
    MORE : 'More',
    RECOMMENDATION_DEFAULT : 'You might like',
    RECOMMENDATION : 'People who\'ve installed this app also like',
    APP_INSTALL_VERSION_LABEL : 'Installed version',
    APP_LATEST_VERSION_LABEL : 'Latest ver.',
    APP_SELECT_GRID_TIP : 'Import apps here',
    APP_SELECT_GRID_TIP_BACKUP : ', You can <span class="button-import-backup link">from an auto backup</span>',
    BUTTON_TRANSFER_LABEL : 'Move to SD card',
    CONFIRM_UNINSTALL : 'Uninstall this app?',
    CONFIRM_UNINSTALL_SYSTEM_APP : 'You\'ve selected a system app, are you sure you want to uninstall? <br/> Deleting Android system apps can damage or "brick" your device.',

    APP_DELETE_PROGRESS : 'Deleting, please wait...',
    APP_DELETE_SUCCESS : 'Uninstalled {1} app(s)',

    APP_EXPORT_PROGRESS : 'Exporting, please wait...',
    APP_EXPORT_SUCCESS : 'Exported {1} app(s)',

    APPS_INSTALL_FAILED : 'Sorry, the following app file is corrupted and couldn\'t be installed:',

    APPS_TRANSFER_TIP_TEXT : 'This app may not run properly if you move it to your SD card. Continue?',
    APPS_TRANSFER_PROCESSING_TEXT : 'Moving...',
    APPS_TRANSFER_SUCCESS_TEXT : 'Moving completed',
    APPS_BATCH_UNINSTALL_FAILED : 'Failed to uninstall the following app(s): ',
    UNINSTALL_FAILED : 'Failed to uninstall app',
    UNINSTALL_FAILED_SYSTEM_APP : 'Please grant SnapPea root privileges and try again',

    APPS_CANCEL_IGNORE_TEXT : 'Unignore',

    APPS_TRANSFER_FAILED_TEXT : 'Failed to move the following app(s): ',
    APPS_EXPORT_ERROR_TEXT : 'Failed to export the following app(s): ',

    APPS_USB_TEXT : 'USB storage mode is on so SnapPea can\'t move or install apps to your device\'s SD card. Please turn off USB storage mode as shown below.',

    XIAOMI_SD_DISABLE : 'Sorry, SnapPea can\'t install apps to your SD card. <br/> Xiaomi\'s default ROM settings prohibit this feature.',

    MOVE_FAILED : 'Failed to move apps',

    EXPORT_ERROR : 'Export failed',
    UNINSTALL_ERROR : 'Uninstall failed',

    GETTING_RECOMMEND : 'Getting recommendations...',
    RECOMMEND_LIST_EMPTY : 'Oh snap, no recs today',
    GET_RECOMMEND_ERROR : 'Oh no, no recs',

    RETURN_ALL : 'All apps',
    SEARCH_TIP_PART : '{1} apps related to "{2}"',

    UPDATE_FROM_SNAPPEA : 'Update from SnapPea',
    UPDATE_FROM_OTHERS : 'Update from another app store',
    UPDATE_CATEGORY_NOT_RECOMMENDED : 'Be cautious when updating',
    NOT_RECOMMENDED_REASON : 'Reason for caution:',

    // VERIFICATION_CODE : '验证码：',
    // CHANGE_VERIFICATION_CODE : '点击更换',

    // CHECK : '查看',
    // YOUR_FAVORITE_APP_TYPE : '您喜欢的应用类型',
    // LAST_APP_LIST : '最新应用专题',
    // SUBMIT : '提交',
    // NEXT : '下一步',
    // CLOSED : '关了',
    // NO : '没有',
    // TRY_AGAIN : '再洗一次',
    // OTHERS : '其他',

    // CHOOSE_BAD_APPS : '选择有问题的应用',
    // WASH_WRONG : '为什么洗错了',
    // WASH_LEAP : '为什么洗漏了',
    // WASH_FEEDBACK_TITLE : '发生什么问题了？',
    // WASH_RESULT_TITLE : '关闭通知栏广告',
    // WASH_ALREADY_CLOSE : '已经关闭了「显示通知」？',
    // WASH_WRONG_TRY_AGAIN : '洗错了？<span class="link button-restart">再洗一次</span>试试，或<span class="link button-feedback">反馈给豌豆们</span>',
    // WASH_INTRO_FEED_BACK : '之前洗错了？请<span class="link button-feedback">反馈给豌豆们</span>',
    // WASH_FEED_BACK_CARD_IGNORE : '能告诉豌豆们为什么暂不处理吗？',
    // WASH_RESULT_ITEM_ATTENTION : '注意：替换后，当前山寨应用的数据或游戏积分会随替换而消失。',
    // WASH_RESULT_ITEM_CONFIRM : '确定替换吗？',
    // WASH_RESULT_ITEM_CHANGE_BY_OTHERS : '该应用被原开发者以外的人篡改过',
    // WASH_RESULT_ITEM_APP_HAS_ADS : '该应用有广告',
    // WASH_RESULT_ITEM_DISABLE_ADS : '关广告',
    // WASH_RESULT_ITEM_IGNORED : '暂不处理',
    // WASH_FEED_BACK_WRONG : '洗错了',
    // WASH_FEED_BACK_LEAP : '洗漏了'
    // WASH_DO_SOMETHING_BAD : '其他坏行为',
    // WASH_NOTIFI_PRIMARY_TITLE : '跟山寨应用和广告应用说白白',
    // WASH_NOTIFI_SECO_TITLE : '豌豆洗白白可以找出您手机中的山寨应用和广告应用，并协助您把它们替换为官方版或无广告版。',
    // WASH_NOTIFI_DO_WASH : '洗一下',
    // WASH_RESULT_INFO_BEFORE_REPLACE : '替换前：',
    // WASH_RESULT_INFO_AFTER_REPLACE : '替换后：',
    // WASH_CLOSE_NOTIFI_TITLE : '请在手机上关闭{{= it.title }}的通知栏消息'

    // "android.permission-group.ACCOUNTS" : "访问您的帐户",
    // "android.permission-group.COST_MONEY" : "需要您付费的服务",
    // "android.permission-group.DEVELOPMENT_TOOLS" : "开发工具",
    // "android.permission-group.LOCATION" : "您的位置",
    // "android.permission-group.HARDWARE_CONTROLS" : "硬件控制",
    // "android.permission-group.MESSAGES" : "读写您的短信和邮件",
    // "android.permission-group.NETWORK" : "访问网络",
    // "android.permission-group.PERSONAL_INFO" : "您的个人信息",
    // "android.permission-group.PHONE_CALLS" : "手机通话",
    // "android.permission-group.STORAGE" : "读写 SD 卡",
    // "android.permission-group.SYSTEM_TOOLS" : "系统工具",
    // "android.permission.ACCESS_CHECKIN_PROPERTIES" : "访问检入属性",
    // "android.permission.ACCESS_COARSE_LOCATION" : "读取基于网络的粗略位置",
    // "android.permission.ACCESS_FINE_LOCATION" : "读取精准的 GPS 位置",
    // "android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" : "访问额外的位置信息提供程序命令",
    // "android.permission.ACCESS_MOCK_LOCATION" : "使用模拟地点进行测试",
    // "android.permission.ACCESS_NETWORK_STATE" : "查看网络状态",
    // "android.permission.ACCESS_SURFACE_FLINGER" : "访问 SurfaceFlinger",
    // "android.permission.ACCESS_WIFI_STATE" : "查看 Wi-Fi 状态",
    // "android.permission.BATTERY_STATS" : "修改电池统计信息",
    // "android.permission.BLUETOOTH" : "创建蓝牙连接",
    // "android.permission.BLUETOOTH_ADMIN" : "蓝牙管理",
    // "android.permission.BRICK" : "变砖",
    // "android.permission.BROADCAST_PACKAGE_REMOVED" : "发送包删除的广播",
    // "android.permission.BROADCAST_STICKY" : "发送置顶广播",
    // "android.permission.CALL_PHONE" : "拨打电话",
    // "android.permission.CALL_PRIVILEGED" : "拨打任何电话",
    // "android.permission.CAMERA" : "拍照",
    // "android.permission.CHANGE_COMPONENT_ENABLED_STATE" : "启用或停用应用程序组件",
    // "android.permission.CHANGE_CONFIGURATION" : "更改用户界面设置",
    // "android.permission.CHANGE_NETWORK_STATE" : "更改网络连接性",
    // "android.permission.CHANGE_WIFI_STATE" : "更改 Wi-Fi 状态",
    // "android.permission.CLEAR_APP_CACHE" : "删除所有应用程序缓存数据",
    // "android.permission.CLEAR_APP_USER_DATA" : "删除应用程序的数据",
    // "android.permission.CONTROL_LOCATION_UPDATES" : "控制位置更新通知",
    // "android.permission.DELETE_CACHE_FILES" : "删除其他应用程序的缓存",
    // "android.permission.DELETE_PACKAGES" : "删除应用程序",
    // "android.permission.DEVICE_POWER" : "开机或关机",
    // "android.permission.DIAGNOSTIC" : "读取/写入诊断所拥有的资源",
    // "android.permission.DISABLE_KEYGUARD" : "停用键盘锁",
    // "android.permission.DUMP" : "检索系统内部状态",
    // "android.permission.EXPAND_STATUS_BAR" : "展开/收拢状态栏",
    // "android.permission.FACTORY_TEST" : "在出厂测试模式下运行",
    // "android.permission.FLASHLIGHT" : "控制闪光灯",
    // "android.permission.FORCE_BACK" : "强制应用程序关闭",
    // "android.permission.GET_ACCOUNTS" : "发现已知帐户",
    // "android.permission.GET_PACKAGE_SIZE" : "计算应用程序存储空间",
    // "android.permission.GET_TASKS" : "检索当前运行的应用程序",
    // "android.permission.HARDWARE_TEST" : "测试硬件",
    // "android.permission.INJECT_EVENTS" : "按键和控制按钮",
    // "android.permission.INSTALL_PACKAGES" : "直接安装应用程序",
    // "android.permission.public_SYSTEM_WINDOW" : "显示未授权的窗口",
    // "android.permission.INTERNET" : "网络通信",
    // "android.permission.MANAGE_APP_TOKENS" : "管理应用程序令牌",
    // "android.permission.MASTER_CLEAR" : "将系统恢复为出厂设置",
    // "android.permission.MODIFY_AUDIO_SETTINGS" : "更改您的音频设置",
    // "android.permission.MODIFY_PHONE_STATE" : "修改手机状态",
    // "android.permission.READ_PHONE_STATE" : "读取手机状态和身份",
    // "android.permission.MOUNT_UNMOUNT_FILESYSTEMS" : "装载和卸载文件系统",
    // "android.permission.PERSISTENT_ACTIVITY" : "让应用程序始终运行",
    // "android.permission.PROCESS_OUTGOING_CALLS" : "拦截外拨电话",
    // "android.permission.READ_CALENDAR" : "访问日历",
    // "android.permission.READ_CONTACTS" : "访问联系人数据",
    // "android.permission.READ_FRAME_BUFFER" : "读取帧缓冲区",
    // "android.permission.READ_INPUT_STATE" : "记录您键入的内容和执行的操作",
    // "android.permission.READ_LOGS" : "读取系统日志文件",
    // "android.permission.READ_OWNER_DATA" : "读取所有者数据",
    // "android.permission.READ_SMS" : "读取短信或彩信",
    // "android.permission.READ_SYNC_SETTINGS" : "读取同步设置",
    // "android.permission.READ_SYNC_STATS" : "读取同步统计信息",
    // "android.permission.REBOOT" : "强行重新启动手机",
    // "android.permission.RECEIVE_BOOT_COMPLETED" : "开机时自动启动",
    // "android.permission.RECEIVE_MMS" : "接收彩信",
    // "android.permission.RECEIVE_SMS" : "接收短信",
    // "android.permission.RECEIVE_WAP_PUSH" : "接收 WAP",
    // "android.permission.RECORD_AUDIO" : "录音",
    // "android.permission.REORDER_TASKS" : "对正在运行的应用程序重新排序",
    // "android.permission.RESTART_PACKAGES" : "重新启动应用程序",
    // "android.permission.SEND_SMS" : "发送短信",
    // "android.permission.SET_ACTIVITY_WATCHER" : "监控所有应用程序的启动",
    // "android.permission.SET_ALWAYS_FINISH" : "关闭所有后台应用程序",
    // "android.permission.SET_ANIMATION_SCALE" : "修改全局动画速度",
    // "android.permission.SET_DEBUG_APP" : "启用应用程序调试",
    // "android.permission.SET_ORIENTATION" : "更改屏幕显示方向",
    // "android.permission.SET_PREFERRED_APPLICATIONS" : "设置首选应用程序",
    // "android.permission.SET_PROCESS_FOREGROUND" : "允许应用程序强行运行到前端",
    // "android.permission.SET_PROCESS_LIMIT" : "限制运行的进程个数",
    // "android.permission.SET_TIME_ZONE" : "设置时区",
    // "android.permission.SET_WALLPAPER" : "设置壁纸",
    // "android.permission.SET_WALLPAPER_HINTS" : "设置有关壁纸大小的提示",
    // "android.permission.SIGNAL_PERSISTENT_PROCESSES" : "向应用程序发送 Linux 信号",
    // "android.permission.STATUS_BAR" : "停用或修改状态栏",
    // "android.permission.SUBSCRIBED_FEEDS_READ" : "读取订阅的供稿",
    // "android.permission.SYSTEM_ALERT_WINDOW" : "显示系统级警报",
    // "android.permission.VIBRATE" : "控制振动器",
    // "android.permission.WAKE_LOCK" : "防止手机休眠",
    // "android.permission.WRITE_APN_SETTINGS" : "写入“接入点名称”设置",
    // "android.permission.WRITE_CALENDAR" : "添加或修改日历活动以及向邀请对象发送电子邮件",
    // "android.permission.WRITE_CONTACTS" : "编辑或写入联系人",
    // "android.permission.WRITE_GSERVICES" : "修改 Google 服务地图",
    // "android.permission.WRITE_OWNER_DATA" : "写入所有者数据",
    // "android.permission.WRITE_SETTINGS" : "修改全局系统设置",
    // "android.permission.WRITE_SMS" : "编辑短信或彩信",
    // "android.permission.WRITE_SYNC_SETTINGS" : "写入同步设置"
});
