/*global define*/
define({
    ADD_LOCAL_MUSIC_TEXT : 'Import songs',
    SING_NAME_TEXT : 'Name',
    ARTIST_TEXT : 'Artist',
    ALBUM_TEXT : 'Album',
    SING_TIME_TEXT : 'Time',
    SING_FORMAT : 'Kind',
    FILE_SELECTOR_DESCRIPTION : 'Select songs from a file or folder',
    DELETE_TIP : 'Delete {1} song(s)? ',
    IMPORT_PROGRESS_TEXT : 'Importing songs, please wait...',
    IMPORT_SUCCESS_TEXT : 'Imported {1} song(s)',
    EXPORT_PROGRESS_TEXT : 'Exporting songs, please wait...',
    EXPORT_SUCCESS_TEXT : 'Exported {1} song(s)',
    DELETE_MUSIC_ERROR : 'Failed to delete songs. ',
    DELETE_MUSIC_ERROR_TEXT : 'Failed to delete the following song(s): ',
    DELETE_PROGRESS_TEXT : 'Deleting songs, please wait...',
    DELETE_SUCCESS_TEXT : 'Deleted {1} song(s). ',
    EXPORT_FAILED_TEXT : 'Failed to export songs。 ',
    SETTING_RING_TEXT : 'Ringtone',
    SETTING_ITEM_CALL_RING_TEXT : 'Set as ringtone',
    SETTING_ITEM_NOTIFY_RING_TEXT : 'Set as notification',
    SETTING_ALARM_RING_TEXT : 'Set as alarm',
    MUSIC_EMPTY_TEXT : 'No songs found on your device. ',
    MUSIC_IMPORT_ERROR_TEXT : 'Sorry, failed to import the following song(s): ',
    MUSIC_EXPORT_ERROR_TEXT : 'Sorry, failed to export the following song(s): ',
    MUSIC_IMPORT_OPERATION_FAILED : 'Failed to import songs',
    NO_SELECTED_MUSIC_TEXT : 'You haven\'t selected any songs',
    SELECT_FILES : 'Select music to import',
    MUSIC_CANNOT_PLAY_TEXT : 'Unsupported music format',

    /*iTunes*/
    START_IMPORT_ITUNES_FAIL : 'iTunes import failed',
    CREATE_TIME : 'In progress...',
    ITUNES_IMPORT : 'Import iTunes music',
    SELECT_LIBRARY_TITLE : 'SnapPea detects that you have multiple iTunes music libraries, select Import',
    ALL_AUDIOS_AND_PLAYLIST : 'All songs and playlists',
    SCANNING_TIP : 'Scanning music library. If you have a large music library this could take a while, please be patient...',
    LESS_CAPACITY : 'Not enough free space',
    SELECT_SOURCE_TITLE : 'Select music to import to your device:',
    SELECT_AUDIOS : 'Select song(s)',
    SELECT_PLAYLIST : 'Select playlist(s)',
    PARSE_ITUNES_SOURCE_FAIL : 'Failed to read iTunes music library',
    IMPORTING_TITLE : 'Importing songs, don\'t disconnect your device...',
    IMPORTING_AUDIOS_TIP : 'If you have a large music library this could take a while, please be patient...',
    CREATING_PLAYLIST_TIP : 'Processing playlists, please be patient...',
    AUDIOS_IMPORT_COMPLETE : 'Importing songs completed',
    AUDIOS_IMPORT_FAILD : 'Failed to import songs',
    CREATE_PLAYLIST_FAILD : 'Failed to import playlist(s)',
    CREATE_PLAYLIST_COMPLETE : 'Importing playlist(s) completed',
    PARSE_EMPTY_LIST : 'Sorry, failed to import songs',
    CREATE_PLAYLIST_FAILD_TIP : 'Songs were imported to your device, but failed to create {1} playlist(s)',
    IMPORT_AUDIOS_FAILD_TIP : 'Failed to import {1} song(s) failed. Continue to import the playlist?',
    SELECT_PLAYLIST_FOR_IMPORT : 'Select the playlists you want to import',
    PLAYLIST_NAME : 'Playlist',
    AUDIOS_COUNT : 'Number of songs',
    IMPORT_COMPLETE : 'Import completed',
    SELECT_PLAYLIST_COUNT_TEXT : '{1} playlist(s) and {2} song(s) selected, with a total size of {3}.',
    SELECT_AUDIOS_COUNT_TEXT : '{1} song(s) selected, with a total size of {2}.',
    ALEADY_EXIT_ITUNES_TASK : 'iTunes is set to import',
    NO_ITUNES_IMPORT_TASK : 'iTunes is not set to import',
    PARSE_ITUNES_SOURCE_FAILD : 'Failed to parse the iTunes resource file',
    NO_ITUNES_FILE : 'No iTunes music library found',
    MOUNT_CANNOT_CREATE_PLAYLIST : 'Imported music in playlists, but unable to create playlists on your device',
    ALREADY_SELECT : 'Selected',
    SELECT_TIP : '{1} playlist(s) and {2} song(s) selected, with a total size of {3}.',
    CONFIRM_IMPORT : 'You\'ve selected to import {1} of music to your device. Importing that much music at once will take an estimated {2} . <br/>Do you want to continue?',
    CAN_NOT_IMPORT_UNDER_WIFI : 'Connect via USB to import iTunes music',

    MUSIC_EMPTY_TEXT_WANXIAODOU : 'Oh? No songs on your phone. '
});
