/*global define*/
define({
    CLOCK_DATE_FORMAT : 'MM dd ',
    OPEN_FOLDER : 'Open folder',
    TOP : 'Return to top',

    WELCOME_PAGE_SHOT : 'Share phone & wallpaper to Sina Weibo',
    WELCOME_PAGE_SHOT_FOR_FACEBOOK : 'Share phone & wallpaper to Facebook',
    SCREEN_SHOT_CLIPBOARD_SUCCESS : 'Copied to clipboard',
    SCREEN_SHOT_FAILD : 'Failed to mirror device',
    SCREEN_SHOT_CANCELD : 'Cancel mirroring device',
    SCREEN_SHOT_TEXT : 'Capture',
    SCREEN_SHOT_SAVE_TO_FILE : 'Save',
    SCREEN_SHOT_SAVE_TO_CLIPBOARD : 'Copy to clipboard',
    SCREEN_SHOT_WITH_WRAP : 'Normal',
    SCEEN_SHOT_WITHOUT_WRAP : 'Screen only',
    SAVE_PATH_FOR_SCREENSHOT : 'Edit screenshots folder...',
    SAVE_PATH_FOR_SCREENSHOT_TIP : 'Screenshot taken! Save all future screenshots to the same folder? ',
    SAVE_SCREEN_SHOT_SUCCESS : 'Screenshot taken',

    FULLSCREEN_BTN_TEXT : 'Full-screen',

    TOOL_BACKUP : 'Backup',
    TOOL_RECOVERY : 'Restore',

    MANAGE_SD_UNCONNECT : 'Your device is not connected, unable to manage files',
    MANAGE_SD_ERROR : 'Oh no, unable to manage files',
    MANAGE_SD_INTERNET : 'Unfortunately you can\'t manage your SD card over the Internet.',

    EDIT_RING : 'Sound Settings',

    AUTO_BACKUP : 'Last auto backup: {1}',
    SHOW_FILE : 'Open',
    TIP_IN_OPEN_FILE1 : 'Sorry, SnapPea can\'t find that backup file',
    TIP_IN_OPEN_FILE2 : 'Possible causes of error: <br /> - File was accidentally deleted <br /> - File path was changed',
    START_AUTO_BACKUP : 'Auto-backup in progress',
    AUTO_BACKUP_SMS_COMPLETE : 'Messages completed',
    AUTO_BACKUP_CONTACTS_COMPLETE : 'Contacts completed',
    AUTO_BACKUP_APP_COMPLETE : 'Apps completed',
    AUTO_BACKUP_PHOTO_COMPLETE : 'Pictures completed',
    AUTO_BACKUP_COMPLETE : 'Auto-backup complete',
    AUTO_BACKUP_TIP_IN_PROGRESS : 'Auto-backup in progress...',

    CONNECT_UR_PHONE : 'Connect your device',
    CONNECTION_TIP : 'SnapPea lets you install apps, send messages, and manage your contacts, pictures, and music. Let\'s get started!',
    CONNECT_PHONE : 'Connect',

    FLASH_TIP_TITLE : 'Flash your device?',
    FLASH_TIP_DESC : 'SnapPea can help you restore your data right now!',

    NEW_IA_QUESTIONNAIRE : 'Hey, do you like the new SnapPea?<span class="link button-like" style="margin-left: 15px">Like</span><span class="link button-unlike"  style="margin-left: 15px">Don\'t Like</span><span class="link button-whatever"  style="margin-left: 15px">No opinion</span>',
    CLOSE_AUTO_START : 'To help you manage your phone, SnapPea will automatically open when you connect your phone. You can turn this off in <span class="link button-setup">Settings</span>',

    GUIDE_BIND_NOW : 'Link phone now',
    GUIDE_BIND_DESC : 'After linking, SnapPea will auto-backup your contacts, messages, and photos. It makes it easy to restore and easy to connect. If this isn\'t your computer, don\'t link!',
    GUIDE_BIND_SUCCESS : 'Congrats, {1} phone is linked. SnapPea will auto-backup your <strong>contacts, messages, and photos</strong>',
    GUIDE_CLOUD_BACKUP_SUCCESS : 'Congrats, you\'ve turned on cloud backup. When you connect your phone to your computer, SnapPea will now auto-backup your apps, contacts, and messages.',
    GUIDE_REG : 'Register for SnapPea',
    GUIDE_REG_DESC : 'To turn on cloud albums you first have to register an account',
    GUIDE_REG_NOW : 'Register now',
    GUIDE_REG_ACCOUNT_PLACEHOLDER : 'Please use your phone number or email address',

    // GUIDE_REG_ACCOUNT_WARN : '您输入的好像不是一个邮箱/手机号',
    // GUIDE_REG_PASSWORD : '密码',
    // GUIDE_REG_PASSWORD_PLACEHOLDER : '最少 6 位数字或字符',
    // GUIDE_REG_PASSWORD_WARN : '请输入密码,密码长度应该大于 6 个字符',
    // GUIDE_REG_PSW_VERIFY_PLACEHOLDER : '再次输入密码',
    // GUIDE_REG_PSW_VERIFY_WARN : '两次输入的密码不一致',
    // GUIDE_REG_NICKNAME_WARN : '昵称不能少于一个字符',
    // GUIDE_REG_CAPTCHA : '验证码',
    // GUIDE_REG_PRAVICY : '同意 <a target="_default" href="#">最终用户条款</a>',
    // GUIDE_REG_LOGIN_WITH_ACCOUNT : '已有账号登陆',
    // GUIDE_REG_LOGIN_WITH_SNS : '合作账号登陆',
    // GUIDE_REG_LOGIN_AND_BACKUP : '登陆后开启云备份',
    // GUIDE_XIBAIBAI_START : '马上开洗',
    // GUIDE_XIBAIBAI_TIP2 :　'豌豆洗白白会帮您找出这些应用,并替换成官方版或没有广告的版本.',
    // GUIDE_XIBAIBAI_TIP3 : '立即使用豌豆洗白白享受放心应用的乐趣吧!',

    GUIDE_STARTER_INSTALL_ALL : 'Install all',
    GUIDE_STARTER_TITLE : 'Must install apps',
    GUIDE_STARTER_TIP : 'Not many apps on your phone. You should try some of these star apps.',
    GUIDE_STARTER_APP_TIP : '{1} installations · {2}% positive reviews<br />{3}',

    // GUIDE_STARTER_GAME_TITLE : '必备游戏',
    // GUIDE_STARTER_GAME_TIP : '大家都在玩的热门游戏,您也装几个试试吧.',

    GUIDE_TIPS : 'Tips',
    GUIDE_TIPS_TIP : 'More tips about SnapPea!',
    GUIDE_TIPS_READ_ALL : 'OK, got it!',
    GUIDE_SUGGESTION : 'View more',
    GUIDE_SUGGESTION_TIP : 'There\'s more content for you to discover!',
    GUIDE_SUGGESTION_READ_ALL : 'I\'m done',
    GUIDE_TEXT_COUNTER : '{1} / {2}',

    CARD_UPDATE_TITLE : 'Update apps',
    CARD_UPDATE_ACTION : 'Update all',
    CARD_UPDATE_DESC : '{1} and {2} others apps have updates.<span class="button-detail link">Details»</span>',
    CARD_APP_TAG_LINE : '{1} · {2} people installed',
    CARD_APP_FOOTER : '{1} · {2}',

    CARD_BACKUP_TITLE : 'No backup for 10 days,',
    //CARD_XIBAIBAI_TITLE : '山寨软件',
    //CARD_XIBAIBAI_DESC : '山寨应用有风险!豌豆洗白白可以把他们更换成官方版或没有广告的版本.',
    //CARD_XIBAIBAI_ACTION : '洗一下',
    //CARD_CLOUD_PHOTO_TITLE : '要自动同步云相册吗?',
    //CARD_CLOUD_PHOTO_DESC : '开启云相册同步后,豌豆荚将自动把您云相册的图片同步到电脑,查看更方便.',
    //CARD_CLOUD_PHOTO_OPEN : '开启',
    CARD_BACKUP_DESC : 'Back up your phone so that you don\'t lose your phone\'s data!',
    CARD_BACKUP_ACTION : 'Backup',
    CARD_TIPS_TITLE : 'About SnapPea\'s features',
    CARD_TIPS_ACTION : 'View now',
    //CARD_WEIBO_TITLE : 'Follow SnapPea!',
    //CARD_WEIBO_DESC : 'Sina Weibo @豌豆荚 <span class="icon-verified"></span>',
    //CARD_WEIBO_ACTION : 'Follow',
    //CARD_WEIBO_ACTION_CLICKED : 'Following',
    //CARD_TIEBA_TITLE : '豌豆荚贴吧求关注!',
    //CARD_TIEBA_DESC : '贴吧神兽,来和萌豆豆聊聊天',
    NO_MORE_1 : '',
    NO_MORE_2 : '',
    NO_MORE_3 : '',
    UPDATED : 'SnapPea was updated!',

    READING_INFO_WARNING : '正在更新信息,请稍后再试'

    //ACCOUNT_UNLOGIN_TEXT : '点击此处开启个性主页'

    // CLICK_TO_CHANGE : 'Click to change',
    // BACKUP_RESOTRE : 'How to back-up and store your phone\'s data',
    // WIFI : 'How to connect your phone via Wi-Fi',
    // APP : 'How to install local apps',
    // CONTACT : 'How to manage your contacts with SnapPea',
    // RINGTONE : 'Why there\'s no sound when you test a ringtone',
    // SETUP_RINGTONE : 'How to quickly set a ringtone',
    // IDENTIFY_CONTACT : 'Why can\'t I dinstguish between contacts, SMS, or apps on my device',
    // ONLINE_GAME : 'What to do when there\'s a problem charing online game credit',
    // TRAFFIC : 'Will \'SnapPea Android client\' consume my data?',
    // EXPORT_CONTACT : 'How to import and export my contacts'
});
