/*global define*/
define({
    WELCOME : '手机体检，快速优化您的手机',
    LAST_TIME_TIP : '上次体检在 <span class="text-warning">{1}</span> 小时前，建议您定期体检，保持手机健康',
    LAST_DAY_TIP : '上次体检在 <span class="text-warning">{1}</span> 天前，建议您定期体检，保持手机健康',
    NEVER_TIP : '您还未进行过体检，建议您定期体检，保持手机健康',
    SCANNING : '正在对您的手机进行扫描，请稍候...',
    SCAN_TIP　: '正在检测第 {1} 项：扫描应用 {2}',
    RAM_TIP : '{1} 款应用占了 {2} 内存，减慢了手机运行速度',
    CACHE_TIP :　'{1} 款应用产生了 {2} 缓存文件，占用了手机内存空间',
    INSTALL_DES : '使用手机体检功能会在您手机上安装「腾讯手机管家」',
    UPDATE_DES : '手机体检功能由腾讯手机管家提供，豌豆荚将升级您手机中的腾讯手机管家至最新版本。',
    UPDATE_TIP : '{1} 款应用可升级，定期升级可有效防范应用漏洞',
    OPTIMIZE_TIP : '您的手机状况可优化，建议您一键优化    ',
    FINISH_TIP : '建议您定期优化手机，保持手机健康    ',
    CANCEL_TIP : '您已取消对手机体检，建议重新扫描',
    ACTION_TIP : '<span class="link button-restart">重新扫描</span><span class="link button-backward">返回</span>',
    OPTIMIZE_TITLE : '可优化项目：{1} 项',
    FINISH_TITLE : '已完成项目：{1} 项',
    SUGGESTION_TITLE : '推荐项目：{1} 项',
    OPTIMIZE : '立即优化',
    UPDATE : '立即升级',
    BACKUP : '立即备份',
    OPTIMIZE_FINISH : '您的手机健康良好，建议您定期优化，保持手机健康    ',
    VIRUS_TIP : '{1} 个应用存在病毒或安全风险，建议卸载',
    OPTIMIZING : '正在优化中，请稍候',
    VENDOR : '腾讯手机管家提供技术支持',
    INSTALLING : '正在为您安装腾讯手机管家',
    INSTALL_ERROR : '安装出现错误，请重试',
    CACHE_FINISH : '清除了 {1} 垃圾文件，为您节省了更多手机空间',
    RAM_FINISH : '释放了 {1} 内存，提升了手机运行速度',
    INSTALL_CANCEL : '安装已取消。',
    WIFI_TIP : '请使用 USB 数据线方式连接手机',
    SCAN_FAILED : '扫描失败',
    OPTIMIZE_ERROR : '优化出错，请检查您的手机上是否正确安装了腾讯手机管家。'
});
